# Generated by Django 5.2.6 on 2025-10-10 04:43

import bi.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('rolName', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('responsabilidad', models.TextField(blank=True, null=True, verbose_name='Responsabilidad principal')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['rolName'],
            },
        ),
        migrations.CreateModel(
            name='InformeCostos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('nombre', models.CharField(editable=False, max_length=255)),
                ('mes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('procesado', models.BooleanField(default=False)),
                ('filas_detectadas', models.PositiveIntegerField(default=0)),
                ('resumen_ventas', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('resumen_gastos', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('resumen_remuneraciones', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'InformeCosto',
                'verbose_name_plural': 'InformeCostos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=bi.models.user_directory_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bi.roles')),
            ],
        ),
    ]
