# Generated by Django 5.2.6 on 2025-09-30 11:04

import bi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=bi.models.user_directory_path),
        ),
    ]
