# Generated by Django 5.2.6 on 2025-10-10 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumenMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')])),
                ('ano', models.IntegerField()),
                ('resumen_ventas', models.DecimalField(decimal_places=2, max_digits=14)),
                ('resumen_gastos', models.DecimalField(decimal_places=2, max_digits=14)),
                ('resumen_remuneraciones', models.DecimalField(decimal_places=2, max_digits=14)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resumen mensual',
                'verbose_name_plural': 'Resúmenes mensuales',
                'ordering': ['-ano', '-mes', 'usuario__username'],
                'unique_together': {('usuario', 'mes', 'ano')},
            },
        ),
    ]
