# Generated by Django 5.2.6 on 2025-10-12 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0002_informecostos'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoEconomico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro', models.PositiveIntegerField(default=0)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(max_length=80)),
                ('naturaleza', models.CharField(choices=[('VE', 'Venta'), ('GA', 'Gasto'), ('RE', 'Remuneración')], max_length=50)),
                ('categoria', models.CharField(choices=[('EdP', 'Estado de Pago'), ('MO', 'Mano de obra'), ('EPP', 'Elementos de protección personal'), ('M', 'Material'), ('H', 'Herramienta'), ('GG', 'Gastos Generales')], max_length=50)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('unidad', models.CharField(max_length=20)),
                ('precio_unitario', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(blank=True)),
                ('informe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bi.informecostos')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('fecha', 'descripcion'), name='unique_fecha_descripcion')],
            },
        ),
    ]
