# Generated by Django 5.2.6 on 2025-10-10 05:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0002_informecostos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informecostos',
            name='anio',
            field=models.PositiveIntegerField(editable=False, validators=[django.core.validators.MinValueValidator(1980), django.core.validators.MaxValueValidator(3000)], verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='informecostos',
            name='mes',
            field=models.PositiveIntegerField(editable=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='informecostos',
            name='resumen_gastos',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='informecostos',
            name='resumen_remuneraciones',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='informecostos',
            name='resumen_ventas',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
