# Generated by Django 5.2.6 on 2025-10-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0003_alter_informecostos_anio_alter_informecostos_mes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoEconomico',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nro', models.PositiveIntegerField(editable=False)),
                ('fecha_venta', models.DateField()),
                ('descripcion', models.TextField(max_length=80)),
                ('naturaleza', models.CharField(choices=[('VE', 'Venta'), ('GA', 'Gasto'), ('RE', 'Remuneración')], max_length=50)),
                ('categoria', models.CharField(choices=[('EdP', 'Estado de Pago'), ('MO', 'Mano de obra'), ('EPP', 'Elementos de protección personal'), ('M', 'Material'), ('H', 'Herramienta'), ('GG', 'Gastos Generales')], max_length=50)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('unidad', models.CharField(max_length=20)),
                ('precio_unitario', models.PositiveIntegerField(default=0)),
                ('total_venta', models.PositiveIntegerField(blank=True)),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('fecha_venta', 'descripcion'), name='unique_fecha_descripcion')],
            },
        ),
    ]
