# Generated by Django 5.2.6 on 2025-10-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0004_movimientoeconomico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoeconomico',
            name='nro',
            field=models.CharField(editable=False, max_length=6),
        ),
    ]
