# Generated by Django 5.2.6 on 2025-10-12 10:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeCostos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('nombre', models.CharField(editable=False, max_length=255)),
                ('mes', models.PositiveIntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], editable=False)),
                ('anio', models.PositiveIntegerField(editable=False, validators=[django.core.validators.MinValueValidator(1980), django.core.validators.MaxValueValidator(3000)], verbose_name='Año')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('procesado', models.BooleanField(default=False)),
                ('filas_detectadas', models.PositiveIntegerField(default=0)),
                ('resumen_ventas', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('resumen_gastos', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('resumen_remuneraciones', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('observaciones', models.TextField(blank=True, default='--', null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'InformeCosto',
                'verbose_name_plural': 'InformeCostos',
                'ordering': ['nombre'],
            },
        ),
    ]
