# Generated by Django 5.2.6 on 2025-11-07 08:27

import bi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0003_movimientoeconomico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informecostos',
            name='archivo_url',
        ),
        migrations.AddField(
            model_name='informecostos',
            name='archivo_gcs',
            field=models.FileField(blank=True, null=True, upload_to='informes/'),
        ),
    ]
